<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="MacBook-Pro-Nikita.local" failures="1" tests="2" name="Surefire test" time="1.988" errors="0" timestamp="2023-03-19T11:02:21 SAMT">
  <testcase classname="tests.base.PlaceOrderTest" name="placeOrder" time="1.092">
    <failure type="java.lang.AssertionError" message="expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]">
      <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]
at tests.base.PlaceOrderTest.placeOrder(PlaceOrderTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- placeOrder -->
  <testcase classname="tests.base.AuthorizationTest" name="loginByUnregisteredUserData" time="0.213"/>
  <testcase classname="tests.base.BaseTest" name="@AfterTest quit" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest quit -->
  <testcase classname="tests.base.BaseTest" name="@AfterTest quit" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest quit -->
</testsuite> <!-- Surefire test -->
