<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-19T11:02:19 SAMT" name="Surefire suite" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="1988">
    <groups>
    </groups>
    <test started-at="2023-03-19T11:02:19 SAMT" name="Surefire test" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="1988">
      <class name="tests.base.AuthorizationTest">
        <test-method is-config="true" signature="openPage()[pri:0, instance:tests.base.AuthorizationTest@7845b21a]" started-at="2023-03-19T11:02:21 SAMT" name="openPage" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="431" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openPage -->
        <test-method signature="loginByUnregisteredUserData()[pri:0, instance:tests.base.AuthorizationTest@7845b21a]" started-at="2023-03-19T11:02:21 SAMT" name="loginByUnregisteredUserData" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginByUnregisteredUserData -->
        <test-method is-config="true" signature="clearCookiesAndLocalStorage()[pri:0, instance:tests.base.AuthorizationTest@7845b21a]" started-at="2023-03-19T11:02:21 SAMT" name="clearCookiesAndLocalStorage" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearCookiesAndLocalStorage -->
      </class> <!-- tests.base.AuthorizationTest -->
      <class name="tests.base.PlaceOrderTest">
        <test-method signature="placeOrder()[pri:0, instance:tests.base.PlaceOrderTest@1f172892]" started-at="2023-03-19T11:02:20 SAMT" name="placeOrder" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="1092" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.base.PlaceOrderTest.placeOrder(PlaceOrderTest.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrder -->
        <test-method is-config="true" signature="clearCookiesAndLocalStorage()[pri:0, instance:tests.base.PlaceOrderTest@1f172892]" started-at="2023-03-19T11:02:21 SAMT" name="clearCookiesAndLocalStorage" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="19" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearCookiesAndLocalStorage -->
        <test-method is-config="true" signature="quit()[pri:0, instance:tests.base.PlaceOrderTest@1f172892]" started-at="2023-03-19T11:02:21 SAMT" name="quit" finished-at="2023-03-19T11:02:21 SAMT" duration-ms="113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- tests.base.PlaceOrderTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
